before_script:
 - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
 - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
 - apt-get update
 - apt-get install -y heroku-toolbelt
 - gem install dpl
 
 staging:
 stage: deploy
 variables:
  HEROKU_API_KEY: $HEROKU
 script:
 - dpl --provider=heroku --app=eternify --api-key=$HEROKU_API_KEY
 - heroku run rake db:migrate --exit-code --app eternify
 only:
 - master